// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	LINKS: KVNamespace;
	TOKEN: "Bearer sahhhhhoiwer892bi#%&&&@^%jsaihvbaksjhlksckjdsas90sskjlda3201";
	DB: D1Database;
}
